import "@/styles/globals.css";

import { Anuphan } from "next/font/google";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { ColorSchemeScript } from "@mantine/core";
import MainProvider from "./_providers/MainProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = Anuphan({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={fontSans.className}>
        <TRPCReactProvider>
          <MainProvider>{children}</MainProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
